{
  "openapi": "3.0.1",
  "info": {
    "version": "1",
    "title": "ROME V4.0 - Situations de travail",
    "description": "Référentiel des environnements dans lequel une personne exerce son travail.<br/> Le contexte de travail englobe les différents éléments physiques, organisationnels et sociaux qui influencent les tâches, les activités et les interactions professionnelles. Il permet de mieux caractériser l’emploi à pourvoir (avantages et contraintes du poste proposé) et réduire les « échecs » de recrutement liés aux conditions de travail.<br/> Le référentiel des contextes de travail se décline en 6 rubriques : Conditions de travail et risques professionnels, Horaires et durées de travail, Lieux et déplacements, Statut d'emploi, Publics spécifiques et Types de structure d’accueil.\r\n\r\n## Aide à l'utilisation de l'API\r\nN'hésitez pas à vous référer au [modèle conceptuel de données](https://francetravail.io/api-peio/v2/pages-document/fichier/607/rome-4-0-contextes-travail-modele-donnees.pdf) de l'API pour définir vos appels aux services.\r\n\r\n## Versions\r\nConsultez ici l’[historique des versions](https://francetravail.io/api-peio/v2/pages-document/fichier/609/rome-4-0-versions.pdf) du ROME 4.0."
  },
  "servers": [
    {
      "url": "https://api.francetravail.io/partenaire/rome-contextes-travail"
    }
  ],
  "paths": {
    "/v1/situations-travail/contexte-travail": {
      "get": {
        "tags": [
          "Contexte de travail"
        ],
        "summary": "Lister les contextes de travail",
        "description": "Permet de lister les contextes de travail.\r\n\r\nSi vous renseignez une ou plusieurs valeurs dans \"champs\", alors vous obtiendrez le résultat pour ces champs.\r\n\r\nSi vous ne renseignez aucune valeur dans \"champs\", alors vous obtiendrez le résultat par défaut. (Sélectionner l'exemple \"***Par défaut***\" pour voir les données retournées)",
        "operationId": "listerContextesTravail",
        "parameters": [
          {
            "name": "champs",
            "in": "query",
            "description": "Sélecteur de champs : il est possible de paramétrer le retour de la requête en définissant les champs souhaités (liste exhaustive des champs possibles : `Allowed values`). <br/> Vous pouvez vous aider des exemples de réponse pour identifier les champs que vous voulez récupérer.",
            "required": false,
            "schema": {
              "type": "string",
              "enum": [
                "categorie",
                "code",
                "libelle"
              ],
              "example": "libelle,code,categorie"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "schema": {
              "type": "string",
              "default": "Bearer "
            },
            "description": "Token d'authentification Bearer"
          }
        ],
        "responses": {
          "200": {
            "description": "Retourne la liste des contextes de travail.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/ContexteTravail"
                  }
                },
                "examples": {
                  "Retour complet": {
                    "value": [
                      {
                        "libelle": "En club sportif",
                        "code": "403091",
                        "categorie": "CONDITIONS_TRAVAIL"
                      }
                    ]
                  },
                  "Retour par défaut": {
                    "value": [
                      {
                        "libelle": "En club sportif",
                        "code": "403091",
                        "categorie": "CONDITIONS_TRAVAIL"
                      }
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request : peut-être causé par un sélecteur de champs incorrect.",
            "content": {
              "application/json": {
                "examples": {
                  "default": {
                    "value": {
                      "message": "L'attribut 'monAttribut' n'est pas selectionnable",
                      "codeMetier": "SELECTOR",
                      "service": "/v1/mon_uri",
                      "code": 400
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "authentification_partenaire": [
              "nomenclatureRome",
              "api_rome-contextes-travailv1"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.francetravail.io/partenaire/rome-contextes-travail",
            "description": "PROD"
          }
        ]
      }
    },
    "/v1/situations-travail/contexte-travail/{code}": {
      "get": {
        "tags": [
          "Contexte de travail"
        ],
        "summary": "Lire un contexte de travail",
        "description": "Permet de lire un contexte de travail depuis son code.\r\n\r\nSi vous renseignez une ou plusieurs valeurs dans \"champs\", alors vous obtiendrez le résultat pour ces champs.\r\n\r\nSi vous ne renseignez aucune valeur dans \"champs\", alors vous obtiendrez le résultat par défaut. (Sélectionner l'exemple \"***Par défaut***\" pour voir les données retournées)",
        "operationId": "lireContexteTravail",
        "parameters": [
          {
            "name": "champs",
            "in": "query",
            "description": "Sélecteur de champs : il est possible de paramétrer le retour de la requête en définissant les champs souhaités (liste exhaustive des champs possibles : `Allowed values`). <br/> Vous pouvez vous aider des exemples de réponse pour identifier les champs que vous voulez récupérer.",
            "required": false,
            "schema": {
              "type": "string",
              "enum": [
                "categorie",
                "code",
                "libelle"
              ],
              "example": "libelle,code,categorie"
            }
          },
          {
            "name": "code",
            "in": "path",
            "description": "Code du contexte de travail.",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "schema": {
              "type": "string",
              "default": "Bearer "
            },
            "description": "Token d'authentification Bearer"
          }
        ],
        "responses": {
          "200": {
            "description": "Retourne les données pour un contexte de travail renseigné.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ContexteTravail"
                },
                "examples": {
                  "Retour complet": {
                    "value": {
                      "libelle": "En club sportif",
                      "code": "403091",
                      "categorie": "CONDITIONS_TRAVAIL"
                    }
                  },
                  "Retour par défaut": {
                    "value": {
                      "libelle": "En club sportif",
                      "code": "403091",
                      "categorie": "CONDITIONS_TRAVAIL"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request : peut-être causé par un sélecteur de champs incorrect.",
            "content": {
              "application/json": {
                "examples": {
                  "default": {
                    "value": {
                      "message": "L'attribut 'monAttribut' n'est pas selectionnable",
                      "codeMetier": "SELECTOR",
                      "service": "/v1/mon_uri",
                      "code": 400
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found.",
            "content": {
              "application/json": {
                "examples": {
                  "default": {
                    "value": {
                      "service": "/v1/mon_uri",
                      "message": "Code inexistant: monCode",
                      "code": 404
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "authentification_partenaire": [
              "nomenclatureRome",
              "api_rome-contextes-travailv1"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.francetravail.io/partenaire/rome-contextes-travail",
            "description": "PROD"
          }
        ]
      }
    },
    "/v1/situations-travail/version": {
      "get": {
        "tags": [
          "Versionning du ROME"
        ],
        "summary": "Récupérer la version actuelle du ROME",
        "description": "Récupère la version actuelle du ROME.",
        "operationId": "lireVersion",
        "parameters": [
          {
            "name": "champs",
            "in": "query",
            "description": "Sélecteur de champs : il est possible de paramétrer le retour de la requête en définissant les champs souhaités (liste exhaustive des champs possibles : `Allowed values`). <br/> Vous pouvez vous aider des exemples de réponse pour identifier les champs que vous voulez récupérer.",
            "required": false,
            "schema": {
              "type": "string",
              "enum": [
                "version",
                "lastModifiedDate",
                "version,lastModifiedDate"
              ],
              "example": "version,lastModifiedDate"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "schema": {
              "type": "string",
              "default": "Bearer "
            },
            "description": "Token d'authentification Bearer"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/VersionRome"
                },
                "examples": {
                  "Retour complet": {
                    "value": {
                      "version": "19",
                      "lastModifiedDate": "2025-05-22T12:04:43.281Z"
                    }
                  },
                  "Retour par défaut": {
                    "value": {
                      "version": "19",
                      "lastModifiedDate": "2025-05-22T12:04:43.281Z"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request : peut-être causé par un sélecteur de champs incorrect",
            "content": {
              "application/json": {
                "examples": {
                  "default": {
                    "value": {
                      "message": "L'attribut 'monAttribut' n'est pas selectionnable",
                      "codeMetier": "SELECTOR",
                      "service": "/v1/mon_uri",
                      "code": 400
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "authentification_partenaire": [
              "nomenclatureRome",
              "api_rome-contextes-travailv1"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://api.francetravail.io/partenaire/rome-contextes-travail",
            "description": "PROD"
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "ContexteTravail": {
        "type": "object",
        "description": "Contexte de travail",
        "properties": {
          "categorie": {
            "type": "string",
            "enum": [
              "CONDITIONS_TRAVAIL",
              "TYPE_BENEFICIAIRE",
              "LIEU_ET_DEPLACEMENT",
              "HORAIRE_ET_DUREE_TRAVAIL",
              "TYPE_STRUCTURE_ACCUEIL",
              "STATUT_EMPLOI"
            ],
            "description": "Catégorie de contexte de travail.",
            "example": "CONDITIONS_TRAVAIL"
          },
          "code": {
            "type": "string",
            "description": "Code unique du contexte de travail.",
            "example": "403091"
          },
          "libelle": {
            "type": "string",
            "description": "Libellé du contexte de travail.",
            "example": "En club sportif"
          }
        }
      },
      "VersionRome": {
        "title": "VersionRome",
        "type": "object",
        "properties": {
          "version": {
            "type": "string",
            "description": "La version actuelle.",
            "example": "19"
          },
          "lastModifiedDate": {
            "type": "string",
            "description": "La date de dernière modification de la version.",
            "format": "date-time"
          }
        },
        "description": "Version du rome"
      }
    },
    "securitySchemes": {
      "authentification_partenaire": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://entreprise.francetravail.fr/connexion/oauth2/access_token?realm=/partenaire",
            "scopes": {
              "nomenclatureRome": "Obligatoire",
              "api_rome-contextes-travailv1": "Obligatoire"
            }
          }
        }
      }
    }
  }
}